name: build-web

on:
  push:
    branches: [ "gh-pages" ]
  pull_request:
    branches: [ "gh-pages" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GOOS: js
      GOARCH: wasm
    defaults:
      run:
        working-directory: ./interpreter/web-repl
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -o ./public/monkey-repl.wasm
